---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - "**.rb"
  - "bin/*"
  - "exe/*"
exclude_paths:
- lamma.gemspec
- "*.md"
- spec/**/*
- Rakefile
