function:
  name: foo-function
  runtime: python27
  role_arn: arn:role:foo
  handler: lambda_function.lambda_handler
  description: Foo
  timeout: 3
  memory_size: 128
  vpc_config:
    subnet_ids:
      - subnet1
      - subnet2
    security_group_ids:
      - sg1
      - sg2
  publish: false
  code:
    source_path: ./source
    prebuild: pip install -r ./requirements.txt -t .
    build_path: ./build
  region: ap-northeast-1
  kms_key_arn: foo
